[package]
name = "chacha_println"
version = "0.1.0"
edition = "2024"

[dependencies]
uefi = { version = "0.30", features = ["alloc"] }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
